### ISSUE TITLE
The syntax highlighting stops working on nested items

### ISSUE THREAD

**Issue by markmals** [lukakerr/Pine#18]
<img width="1249" alt="screen shot 2018-09-01 at 7 05 41 pm" src="https://user-images.githubusercontent.com/39869007/44951476-189b1700-ae1a-11e8-9527-b0f3675ed5ff.png">

**Comment by lukakerr** [comment]
I assume you're using tabs for indentation, as with spaces the syntax highlighting works, except even with spaces the actual bullet `*` or `-` still doesn't get syntax highlighted for nested items. Unfortunately I use the [Highlightr](https://github.com/raspu/Highlightr) library for syntax highlighting, so there's not much I can do apart from raise an issue, or convert tabs to spaces automatically which I'm sure some people wouldn't like

**Comment by markmals** [comment]
Yes, using tabs. Highlightr seems to be relatively well maintained still, so perhaps raising an issue there might convince them to fix this.

Have you considered any other syntax highlighting libraries? It's not necessarily more currently maintained or more stable, but [SyntaxKit](https://github.com/soffes/SyntaxKit) was built specifically for [a Markdown app](http://usewhiskey.com) and supports any `tmLanguage` and `tmTheme` files, which are pretty ubiquitous and used by Visual Studio Code. Also it's fully native and doesn't rely on JavaScript.

**Comment by lukakerr** [comment]
Since I use Highlightr for the app themeing as well, it might be tricky to move to a different library, but I’ll take a look at them and see if it’s possible, since using tmLanguage/tmTheme files would open up the ability to use colour schemes already out there

**Comment by lukakerr** [comment]
Just FYI, this has been fixed. I fixed it myself in the end in a PR to highlight.js - https://github.com/highlightjs/highlight.js/pull/2004. The result is shown below:

<img width="1362" alt="Screen Shot 2019-03-13 at 3 53 03 pm" src="https://user-images.githubusercontent.com/20056300/54254610-7918c700-45a8-11e9-9a7c-b805fc2bb52e.png">
