### ISSUE TITLE
Theme for GitLab

### ISSUE THREAD

**Issue by TofPlay** [lukakerr/Pine#21]
Do you have a theme for GitLab?
I also found that GitHub and GitLab did not support the markdown in the same way
So the rendering is not exactly the same
Suggestion: Add in preferences a "compatibility" option with the possibility of choosing "GitHub" or "GitLab" (or something else)

**Comment by lukakerr** [comment]
I don’t plan on supporting GitLab flavoured markdown, so that won’t be added. I do plan to add a syntax theme for GitLab sometime in the future though.

**Comment by lukakerr** [comment]
GitLab Flavored Markdown won't be supported, so i'll close this.
