### ISSUE TITLE
Light themes display default text as white in Preview

### ISSUE THREAD

**Issue by jpinnix** [lukakerr/Pine#36]
This appears to be the case for all light themes. And something is off with the default text color for `atom-one-light` in the editor as well.

`solarized-light` theme:
<img width="1194" alt="screen shot 2019-02-20 at 11 26 56 am" src="https://user-images.githubusercontent.com/4436/53111654-1bdaaa00-3503-11e9-8168-79cd5c307788.png">

`atom-one-light` theme:
<img width="1240" alt="screen shot 2019-02-20 at 11 30 42 am" src="https://user-images.githubusercontent.com/4436/53111655-1bdaaa00-3503-11e9-976a-304247ebc113.png">

**Comment by lukakerr** [comment]
Hmm, I can't seem to reproduce this, below is what's shown for me using the solarized-light theme:

<img width="1240" alt="screen shot 2019-02-21 at 7 56 53 am" src="https://user-images.githubusercontent.com/20056300/53123948-58afab00-35ae-11e9-87f6-02285f5fe7ad.png">

Is this with Twig v0.0.5? Also what macOS version are you running?

**Comment by jpinnix** [comment]
Twig v0.0.5
macOS Mojave 10.14.3 (18D109)

**Comment by jpinnix** [comment]
Just verified: If macOS is in Light mode, you can open Twig and light themes work correctly. You can even switch to Dark mode and they work fine.

The issue is when you are in Dark mode and then open Twig.

**Comment by jpinnix** [comment]
With macOS in Light mode:
* Open twig, `atom-one-dark` and `atom-one-light` work correctly
* Change to Dark Mode, `atom-one-dark` works, `atom-one-light` doesn't

With macOS in Dark mode:
* Open twig, `atom-one-dark` works, `atom-one-light` doesn't
* change to Light mode, `atom-one-dark` and `atom-one-light` work correctly

**Comment by lukakerr** [comment]
I managed to look into this today and believe I've fixed it in ffc1985. The logic wasn't 100% right when the theme changed or the system appearance changed. This will be included in the next release, and if you still experience it feel free to re-open this issue or create a new one

**Comment by jpinnix** [comment]
> With macOS in Light mode:
> 
>     * Open twig, `atom-one-dark` and `atom-one-light` work correctly
> 
>     * Change to Dark Mode, `atom-one-dark` works, `atom-one-light` doesn't
> 
> 
> With macOS in Dark mode:
> 
>     * Open twig, `atom-one-dark` works, `atom-one-light` doesn't
> 
>     * change to Light mode, `atom-one-dark` and `atom-one-light` work correctly

I'm still experiencing this. I completely uninstalled Twig. Downloaded Pine v0.0.8. To clarify, this seems to be related to Mojave dark/light modes.

**Comment by jpinnix** [comment]
Also, I don't have permissions to re-open this issue.

**Comment by lukakerr** [comment]
@jpinnix this fix hasn’t been released yet. It was pushed right after the 0.0.8 release.

**Comment by jpinnix** [comment]
Doh. Okay, that makes sense. Sorry!
