### ISSUE TITLE
iPad App  with „marzipan“

### ISSUE THREAD

**Issue by F3000** [lukakerr/Pine#38]
Hi, 

do you plan an iPad app ?

**Comment by lukakerr** [comment]
If Marzipan makes it easy then yes I'd like to include iPad as a target. But as Marzipan information isn't public, I can't say for a definite

**Comment by arguiot** [comment]
I believe Marzipan only works when you want to translate your iOS app to macOS app. The opposite isn't possible because AppKit doesn't work on iOS

**Comment by lukakerr** [comment]
@arguiot is correct, so this won't happen.
