### ISSUE TITLE
Support RTL documents

### ISSUE THREAD

**Issue by itaisteinherz** [lukakerr/Pine#44]
Just downloaded Twig, and I have to say it looks awesome! Thanks for making it @lukakerr 🔥

However, currently when editing RTL documents, the text stays oriented to the left (instead of to the right).

**Comment by lukakerr** [comment]
Thanks! Admittedly I don't know too much about RTL languages. Before I start on this could you let me know:

- Do other macOS apps (e.g. TextEdit) automatically detect the language used and switch to a RTL layout? Or do you have to specify whether you want to use a RTL writing direction?

**Comment by itaisteinherz** [comment]
> Do other macOS apps (e.g. TextEdit, Pages, Terminal) automatically detect the language used and switch to a RTL layout? Or do you have to specify whether you want to use a RTL writing direction?

- TextEdit doesn't detect the language used, but you can easily change the writing direction in `Format > Text > Writing Direction`.
- Pages automatically detects the writing direction of a paragraph based on the first character, but you can change the direction using the arrow button in the `Alignment` section of the `Format` tab (on the right).
- Terminal always sets the writing direction to be LTR, and I don't think there's a way to change it.

**Comment by lukakerr** [comment]
Hmm, not much consistency! I'll implement the option to change the writing direction via a menubar item, right click menu or a keyboard shortcut.

In fact currently you can right click and select `Writing Direction > Right to Left`, although it doesn't work as expected due to the syntax highlighting library used. I've filed an issue at https://github.com/raspu/Highlightr/issues/61, and actually fixed it myself on [my own fork](https://github.com/lukakerr/Highlightr/commit/5c35cecb0e345892122eb47533e87c06ef4286fd), so this should be fixed very soon.

**Comment by lukakerr** [comment]
This has now been added. You can set it via the menu bar `Format > Writing Direction` or via right click `Writing Direction`. It will be included in the next release, below is a screenshot.

<img width="788" alt="Screen Shot 2019-03-13 at 5 07 45 pm" src="https://user-images.githubusercontent.com/20056300/54257160-8e92ee80-45b2-11e9-8048-3b496e022142.png">

If there are any problems feel free to open a new issue after the next release.

**Comment by itaisteinherz** [comment]
Awesome, thanks! I'll check it out once the next release is out.

**Comment by itaisteinherz** [comment]
<img width="832" alt="Screenshot" src="https://user-images.githubusercontent.com/22768990/54866579-37dd9f80-4d7e-11e9-8874-c6c9cc3a55d3.png">

RTL text on the latest version of Pine (`v0.0.9`) looks good, except for a few problems I encountered:

- Characters in the editing pane are dedented into the preview pane, making a part of the first character in each line invisible.
- When doing any action other than editing (i.e. changing the theme), the writing direction reverts to being LTR. It would be useful to just have the writing direction consistent and automatically set (I'm not sure how this can be done in Swift, but in HTML you can set an element's [`dir`](https://www.w3schools.com/tags/att_global_dir.asp) attribute to `auto` to have the browser align the text based on the contents).

**Comment by lukakerr** [comment]
I've implemented the option to set the writing direction in preferences in 1bf69d4. This way it is persisted and set automatically. You can also change it temporarily by using the right click menu or menu bar item, but this will revert back to the one saved in preferences at a later time.

The issue of part of the character being hidden should also be fixed now.
