### ISSUE TITLE
Dragging into xxxx.md is not supported to open the document.

### ISSUE THREAD

**Issue by maboloshi** [lukakerr/Pine#46]
see title.

**Comment by lukakerr** [comment]
Are you talking about dragging a markdown file into the dock icon? If so, this seems to be working for me with the latest release (0.0.7). The markdown file gets successfully opened

**Comment by maboloshi** [comment]
I mean the pine app window.

**Comment by lukakerr** [comment]
This won't be added/fixed. You can open a markdown document by dragging it to the app icon in the Dock, or through the multiple menu items/keyboard shortcuts. Dragging a markdown file into the editor will just insert the file's path as text.
