### ISSUE TITLE
Typing "</div" exposes JS in preview

### ISSUE THREAD

**Issue by Clashsoft** [lukakerr/Pine#49]
Pretty self-explanatory, see screenshot below.

![Screenshot 2019-03-22 at 22 06 39](https://user-images.githubusercontent.com/4145923/54853055-f9e56a80-4cee-11e9-96a3-92910ba3f84b.png)

It also works for other HTML tags (I tested `<table`, `<tr`, `<div`, `<blockquote`, `<pre`, `<p` and their closing equivalents), but not all (e.g. `<a`, `<span`, `<b`, `<s`, `<i`).

**Comment by lukakerr** [comment]
Thanks for reporting, this was fixed in b0bcd44, it just hasn’t been released yet.
