### ISSUE TITLE
Files in sidebar not sorted alphabetically

### ISSUE THREAD

**Issue by jpinnix** [lukakerr/Pine#54]
When I open a folder of files, it does not display them alphabetically.

<img width="197" alt="Screen Shot 2019-03-31 at 6 09 01 PM" src="https://user-images.githubusercontent.com/4436/55296513-2f214500-53e0-11e9-8ef9-645af6a31b1a.png">

**Comment by lukakerr** [comment]
Should be fixed in 45b3edd
