### ISSUE TITLE
Colon disables some Markdown-Formatting

### ISSUE THREAD

**Issue by noestreich** [lukakerr/Pine#59]
Some Markdown-Formatting like **bold** and _italic_ gets disabled if a colon is within the asterisks: 

This: `**i am a test**` produces: **i am a test**
but 
This: `**i am a test:**` just produces: `**i am a test:**`

<img width="635" alt="Bildschirmfoto 2019-05-03 um 07 49 34" src="https://user-images.githubusercontent.com/309419/57121481-31c4e080-6d78-11e9-9c86-e24532316eb4.png">

**Comment by lukakerr** [comment]
This was a bug in the GitHub emoji handling and is fixed in https://github.com/lukakerr/cmark-gfm-swift/commit/64a89d99aba5526ce9a2787dacae1e4ff68130cd. It will be included in the next release.

**Comment by kerryj89** [comment]
@lukakerr Just FYI - this is still an issue
