### ISSUE TITLE
Text on current line seems to bounce up and down rapidly while typing.

### ISSUE THREAD

**Issue by NSExceptional** [lukakerr/Pine#65]

**Comment by lukakerr** [comment]
Could you attach a gif or image showing the problem? I cannot reproduce it without any description of your macOS environment or what exactly is occurring.

**Comment by NSExceptional** [comment]
Strangely I can't reproduce it either at the moment. I'll close this for now for your peace of mind, and if I see it again, I'll reopen it and post a GIF.

**Comment by petersf-libre** [comment]
Was about to post an issue for this. I'm having the same problem and managed to record it.
![Screen Recording 2020-01-18 at 11 16 04 PM-Animated Image (Large)](https://user-images.githubusercontent.com/54224726/72674819-824dac80-3a73-11ea-9893-33e333d5866a.gif)
