### ISSUE TITLE
Onboarding idea -- Showcase features in example .md doc?

### ISSUE THREAD

**Issue by peterkos** [lukakerr/Pine#69]
Currently, Pine just opens to a completely blank screen. It'd be nice if there was an example markdown document to a) showcase Pine's features, and b) give a launching point for the user, i.e., "click here to create your first doc".

**Comment by lukakerr** [comment]
A splash screen was added in #70 and is now in `master`. This lets you open a sample document, create a new document, open an existing document or open a recent document.
